### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by jamesb93** [d3rp/HPR_VST3#1]
Hi there,

This is really great. Without stepping on your toes perhaps you will find this code interesting or useful as a resource:

https://github.com/flucoma/flucoma-core

We have several algos including HPSS (with several masking modes) in C++.

Otherwise this is a nifty plugin and something seemingly unexplored in many sound production circles.

**Comment by turuluu** [comment]
Thank you for the kind words! I checked some of the algorithms and they seemed very interesting, but I did not have the chance to try them out yet. Flucoma seems to also depend on, for example, Eigen. I'm trying to steer off from any dependencies I don't absolutely need. I'll have another look later.
